sudo: required
services: 
  - docker

before_install:
  - docker build -t adilcan/frontend1 -f Dockerfile.dev . 

script:
  - docker run -e CI=true adilcan/frontend1 npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend" 
  env: "Frontend-env"
  bucket-name: "elasticbeanstalk-us-east-1-435264530466"
  bucket-path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

